insert into cars (id, model, color, release_year) values (1, 'X5', 'Khaki', 2013);
insert into cars (id, model, color, release_year) values (2, '612 Scaglietti', 'Orange', 2009);
insert into cars (id, model, color, release_year) values (3, 'Caravan', 'Violet', 1997);
insert into cars (id, model, color, release_year) values (4, 'SL-Class', 'Turquoise', 1994);
insert into cars (id, model, color, release_year) values (5, 'Integra', 'Crimson', 2001);
insert into cars (id, model, color, release_year) values (6, 'LeMans', 'Aquamarine', 1992);
insert into cars (id, model, color, release_year) values (7, 'M3', 'Puce', 2011);
insert into cars (id, model, color, release_year) values (8, 'Roadmaster', 'Puce', 1993);
insert into cars (id, model, color, release_year) values (9, 'i-350', 'Turquoise', 2006);
insert into cars (id, model, color, release_year) values (10, 'NSX', 'Blue', 1995);
insert into cars (id, model, color, release_year) values (11, 'JX', 'Khaki', 2013);
insert into cars (id, model, color, release_year) values (12, 'QX', 'Blue', 2000);
insert into cars (id, model, color, release_year) values (13, 'Cultus', 'Orange', 1985);
insert into cars (id, model, color, release_year) values (14, 'Durango', 'Puce', 1999);
insert into cars (id, model, color, release_year) values (15, 'Grand Voyager', 'Pink', 1993);
insert into cars (id, model, color, release_year) values (16, 'Vibe', 'Pink', 2006);
insert into cars (id, model, color, release_year) values (17, '240SX', 'Red', 1998);
insert into cars (id, model, color, release_year) values (18, 'Esprit', 'Orange', 1992);
insert into cars (id, model, color, release_year) values (19, 'Camaro', 'Green', 1978);
insert into cars (id, model, color, release_year) values (20, 'Sebring', 'Green', 2002);
insert into cars (id, model, color, release_year) values (21, 'Truck', 'Mauv', 1996);
insert into cars (id, model, color, release_year) values (22, 'SL-Class', 'Indigo', 2008);
insert into cars (id, model, color, release_year) values (23, 'Concorde', 'Violet', 2004);
insert into cars (id, model, color, release_year) values (24, 'RX Hybrid', 'Teal', 2011);
insert into cars (id, model, color, release_year) values (25, 'Mirage', 'Violet', 1990);
insert into cars (id, model, color, release_year) values (26, 'M3', 'Violet', 1997);
insert into cars (id, model, color, release_year) values (27, 'Civic', 'Goldenrod', 1998);
insert into cars (id, model, color, release_year) values (28, 'Envoy', 'Indigo', 1999);
insert into cars (id, model, color, release_year) values (29, 'New Beetle', 'Indigo', 2006);
insert into cars (id, model, color, release_year) values (30, 'Camry', 'Mauv', 1992);
insert into cars (id, model, color, release_year) values (31, 'Mirage', 'Turquoise', 1985);
insert into cars (id, model, color, release_year) values (32, 'R-Class', 'Blue', 2010);
insert into cars (id, model, color, release_year) values (33, 'Colorado', 'Goldenrod', 2012);
insert into cars (id, model, color, release_year) values (34, 'Rodeo', 'Purple', 1996);
insert into cars (id, model, color, release_year) values (35, 'F150', 'Indigo', 2006);
insert into cars (id, model, color, release_year) values (36, 'F350', 'Crimson', 1993);
insert into cars (id, model, color, release_year) values (37, 'MX-6', 'Orange', 1996);
insert into cars (id, model, color, release_year) values (38, 'Grand Vitara', 'Orange', 2008);
insert into cars (id, model, color, release_year) values (39, 'LSS', 'Pink', 1998);
insert into cars (id, model, color, release_year) values (40, 'Yukon', 'Maroon', 1995);
insert into cars (id, model, color, release_year) values (41, 'Avalon', 'Pink', 2000);
insert into cars (id, model, color, release_year) values (42, 'Jimmy', 'Puce', 1995);
insert into cars (id, model, color, release_year) values (43, 'LeSabre', 'Aquamarine', 1994);
insert into cars (id, model, color, release_year) values (44, 'Tribeca', 'Crimson', 2012);
insert into cars (id, model, color, release_year) values (45, 'Sunbird', 'Aquamarine', 1986);
insert into cars (id, model, color, release_year) values (46, 'Legacy', 'Indigo', 2011);
insert into cars (id, model, color, release_year) values (47, 'Previa', 'Purple', 1992);
insert into cars (id, model, color, release_year) values (48, 'V70', 'Purple', 2007);
insert into cars (id, model, color, release_year) values (49, 'Altima', 'Green', 2009);
insert into cars (id, model, color, release_year) values (50, 'Ram 2500', 'Pink', 2009);
insert into cars (id, model, color, release_year) values (51, 'GS', 'Purple', 2011);
insert into cars (id, model, color, release_year) values (52, 'Justy', 'Mauv', 1990);
insert into cars (id, model, color, release_year) values (53, 'M5', 'Aquamarine', 2008);
insert into cars (id, model, color, release_year) values (54, 'Corrado', 'Crimson', 1992);
insert into cars (id, model, color, release_year) values (55, 'Sidekick', 'Yellow', 1989);
insert into cars (id, model, color, release_year) values (56, 'Yukon XL 2500', 'Fuscia', 2007);
insert into cars (id, model, color, release_year) values (57, 'Venture', 'Puce', 2000);
insert into cars (id, model, color, release_year) values (58, 'Escalade', 'Teal', 2007);
insert into cars (id, model, color, release_year) values (59, 'Sentra', 'Blue', 1994);
insert into cars (id, model, color, release_year) values (60, 'Caravan', 'Maroon', 2007);
insert into cars (id, model, color, release_year) values (61, 'Cooper', 'Turquoise', 2007);
insert into cars (id, model, color, release_year) values (62, 'Range Rover', 'Goldenrod', 1991);
insert into cars (id, model, color, release_year) values (63, 'Flex', 'Yellow', 2011);
insert into cars (id, model, color, release_year) values (64, '626', 'Khaki', 1990);
insert into cars (id, model, color, release_year) values (65, 'SSR', 'Teal', 2004);
insert into cars (id, model, color, release_year) values (66, '5 Series', 'Crimson', 2007);
insert into cars (id, model, color, release_year) values (67, 'xD', 'Teal', 2009);
insert into cars (id, model, color, release_year) values (68, '4Runner', 'Crimson', 2005);
insert into cars (id, model, color, release_year) values (69, 'Town Car', 'Orange', 2004);
insert into cars (id, model, color, release_year) values (70, '740', 'Fuscia', 1992);
insert into cars (id, model, color, release_year) values (71, 'L-Series', 'Teal', 2004);
insert into cars (id, model, color, release_year) values (72, 'XT', 'Crimson', 1989);
insert into cars (id, model, color, release_year) values (73, '530', 'Pink', 2001);
insert into cars (id, model, color, release_year) values (74, 'Cabriolet', 'Goldenrod', 1992);
insert into cars (id, model, color, release_year) values (75, 'CR-V', 'Turquoise', 2011);
insert into cars (id, model, color, release_year) values (76, 'Ram Wagon B350', 'Maroon', 1993);
insert into cars (id, model, color, release_year) values (77, 'Laser', 'Red', 1984);
insert into cars (id, model, color, release_year) values (78, 'Camaro', 'Yellow', 1971);
insert into cars (id, model, color, release_year) values (79, 'Accent', 'Mauv', 2010);
insert into cars (id, model, color, release_year) values (80, 'Festiva', 'Goldenrod', 1988);
insert into cars (id, model, color, release_year) values (81, 'Alpina B7', 'Purple', 2008);
insert into cars (id, model, color, release_year) values (82, 'Esprit', 'Pink', 1995);
insert into cars (id, model, color, release_year) values (83, 'i-Series', 'Indigo', 2006);
insert into cars (id, model, color, release_year) values (84, 'Bravada', 'Pink', 2004);
insert into cars (id, model, color, release_year) values (85, 'F250', 'Green', 2000);
insert into cars (id, model, color, release_year) values (86, 'Continental GT', 'Maroon', 2010);
insert into cars (id, model, color, release_year) values (87, 'Eclipse', 'Maroon', 1989);
insert into cars (id, model, color, release_year) values (88, 'Eldorado', 'Teal', 2000);
insert into cars (id, model, color, release_year) values (89, 'DeVille', 'Maroon', 1999);
insert into cars (id, model, color, release_year) values (90, 'Celica', 'Orange', 2001);
insert into cars (id, model, color, release_year) values (91, 'Cavalier', 'Mauv', 2001);
insert into cars (id, model, color, release_year) values (92, '9-5', 'Khaki', 2000);
insert into cars (id, model, color, release_year) values (93, 'M-Class', 'Teal', 2007);
insert into cars (id, model, color, release_year) values (94, 'A8', 'Red', 2000);
insert into cars (id, model, color, release_year) values (95, 'A6', 'Crimson', 2006);
insert into cars (id, model, color, release_year) values (96, 'Corolla', 'Teal', 2001);
insert into cars (id, model, color, release_year) values (97, 'Viper RT/10', 'Aquamarine', 1993);
insert into cars (id, model, color, release_year) values (98, 'xD', 'Turquoise', 2008);
insert into cars (id, model, color, release_year) values (99, 'Passat', 'Khaki', 2012);
insert into cars (id, model, color, release_year) values (100, 'Altima', 'Maroon', 1999);
insert into cars (id, model, color, release_year) values (101, 'Nubira', 'Pink', 2000);
insert into cars (id, model, color, release_year) values (102, 'Cooper', 'Maroon', 2012);
insert into cars (id, model, color, release_year) values (103, 'Elantra', 'Blue', 1993);
insert into cars (id, model, color, release_year) values (104, 'Astra', 'Crimson', 2009);
insert into cars (id, model, color, release_year) values (105, 'Firebird', 'Goldenrod', 1997);
insert into cars (id, model, color, release_year) values (106, 'GTO', 'Fuscia', 1965);
insert into cars (id, model, color, release_year) values (107, 'Outlook', 'Fuscia', 2008);
insert into cars (id, model, color, release_year) values (108, 'S-Class', 'Khaki', 2012);
insert into cars (id, model, color, release_year) values (109, '2500 Club Coupe', 'Turquoise', 1994);
insert into cars (id, model, color, release_year) values (110, 'Expedition EL', 'Red', 2007);
insert into cars (id, model, color, release_year) values (111, 'Justy', 'Red', 1987);
insert into cars (id, model, color, release_year) values (112, '530', 'Puce', 2002);
insert into cars (id, model, color, release_year) values (113, 'Truck', 'Violet', 1985);
insert into cars (id, model, color, release_year) values (114, 'Charger', 'Indigo', 1968);
insert into cars (id, model, color, release_year) values (115, 'Type 2', 'Violet', 1989);
insert into cars (id, model, color, release_year) values (116, 'Golf', 'Violet', 2004);
insert into cars (id, model, color, release_year) values (117, 'Alero', 'Khaki', 2000);
insert into cars (id, model, color, release_year) values (118, 'SL-Class', 'Aquamarine', 2012);
insert into cars (id, model, color, release_year) values (119, 'XG350', 'Goldenrod', 2004);
insert into cars (id, model, color, release_year) values (120, 'XC60', 'Violet', 2011);
insert into cars (id, model, color, release_year) values (121, 'Camry Solara', 'Maroon', 2008);
insert into cars (id, model, color, release_year) values (122, 'Montero Sport', 'Mauv', 2004);
insert into cars (id, model, color, release_year) values (123, 'Justy', 'Green', 1990);
insert into cars (id, model, color, release_year) values (124, 'Tiburon', 'Goldenrod', 2007);
insert into cars (id, model, color, release_year) values (125, 'Mariner', 'Khaki', 2006);
insert into cars (id, model, color, release_year) values (126, 'LR2', 'Maroon', 2009);
insert into cars (id, model, color, release_year) values (127, '928', 'Aquamarine', 1994);
insert into cars (id, model, color, release_year) values (128, '8 Series', 'Puce', 1992);
insert into cars (id, model, color, release_year) values (129, 'Escort', 'Maroon', 1998);
insert into cars (id, model, color, release_year) values (130, 'Firebird', 'Maroon', 1989);
insert into cars (id, model, color, release_year) values (131, '5000S', 'Goldenrod', 1986);
insert into cars (id, model, color, release_year) values (132, 'Galant', 'Khaki', 1984);
insert into cars (id, model, color, release_year) values (133, 'Pajero', 'Violet', 2005);
insert into cars (id, model, color, release_year) values (134, 'Cavalier', 'Green', 2003);
insert into cars (id, model, color, release_year) values (135, 'Thunderbird', 'Goldenrod', 1993);
insert into cars (id, model, color, release_year) values (136, '9-3', 'Pink', 1999);
insert into cars (id, model, color, release_year) values (137, 'Accord', 'Fuscia', 1988);
insert into cars (id, model, color, release_year) values (138, 'Tiguan', 'Mauv', 2012);
insert into cars (id, model, color, release_year) values (139, 'Concorde', 'Purple', 2004);
insert into cars (id, model, color, release_year) values (140, 'Eurovan', 'Pink', 1994);
insert into cars (id, model, color, release_year) values (141, 'H3T', 'Red', 2009);
insert into cars (id, model, color, release_year) values (142, 'Civic Si', 'Violet', 2006);
insert into cars (id, model, color, release_year) values (143, 'Swift', 'Fuscia', 1990);
insert into cars (id, model, color, release_year) values (144, 'Corvette', 'Mauv', 1984);
insert into cars (id, model, color, release_year) values (145, 'Murciélago', 'Fuscia', 2002);
insert into cars (id, model, color, release_year) values (146, 'MX-5', 'Turquoise', 2007);
insert into cars (id, model, color, release_year) values (147, '626', 'Green', 1987);
insert into cars (id, model, color, release_year) values (148, 'Canyon', 'Turquoise', 2010);
insert into cars (id, model, color, release_year) values (149, 'F150', 'Red', 2009);
insert into cars (id, model, color, release_year) values (150, 'MX-5', 'Teal', 2001);
insert into cars (id, model, color, release_year) values (151, 'F450', 'Orange', 2009);
insert into cars (id, model, color, release_year) values (152, 'Aspen', 'Fuscia', 2007);
insert into cars (id, model, color, release_year) values (153, 'XJ', 'Blue', 2011);
insert into cars (id, model, color, release_year) values (154, 'GS', 'Fuscia', 2007);
insert into cars (id, model, color, release_year) values (155, 'Highlander', 'Khaki', 2005);
insert into cars (id, model, color, release_year) values (156, 'Sebring', 'Puce', 2001);
insert into cars (id, model, color, release_year) values (157, 'Prius Plug-in', 'Mauv', 2012);
insert into cars (id, model, color, release_year) values (158, 'SC', 'Mauv', 1995);
insert into cars (id, model, color, release_year) values (159, 'Continental', 'Turquoise', 2008);
insert into cars (id, model, color, release_year) values (160, 'ES', 'Maroon', 1997);
insert into cars (id, model, color, release_year) values (161, 'Reatta', 'Turquoise', 1989);
insert into cars (id, model, color, release_year) values (162, 'GT350', 'Aquamarine', 1969);
insert into cars (id, model, color, release_year) values (163, 'Tercel', 'Red', 1993);
insert into cars (id, model, color, release_year) values (164, 'Elantra', 'Orange', 2009);
insert into cars (id, model, color, release_year) values (165, 'Familia', 'Blue', 1990);
insert into cars (id, model, color, release_year) values (166, 'tC', 'Turquoise', 2009);
insert into cars (id, model, color, release_year) values (167, 'EX', 'Teal', 2009);
insert into cars (id, model, color, release_year) values (168, 'Ram Van 1500', 'Puce', 2000);
insert into cars (id, model, color, release_year) values (169, 'Grand Cherokee', 'Red', 2003);
insert into cars (id, model, color, release_year) values (170, 'DeVille', 'Violet', 1992);
insert into cars (id, model, color, release_year) values (171, 'LX', 'Purple', 2002);
insert into cars (id, model, color, release_year) values (172, 'Avalon', 'Crimson', 2005);
insert into cars (id, model, color, release_year) values (173, 'Suburban 1500', 'Pink', 2002);
insert into cars (id, model, color, release_year) values (174, '2500', 'Blue', 1993);
insert into cars (id, model, color, release_year) values (175, 'MKS', 'Purple', 2012);
insert into cars (id, model, color, release_year) values (176, 'IS F', 'Purple', 2011);
insert into cars (id, model, color, release_year) values (177, 'XL7', 'Yellow', 2008);
insert into cars (id, model, color, release_year) values (178, 'Corolla', 'Fuscia', 1995);
insert into cars (id, model, color, release_year) values (179, 'Continental', 'Violet', 1996);
insert into cars (id, model, color, release_year) values (180, 'Neon', 'Pink', 1999);
insert into cars (id, model, color, release_year) values (181, 'Gallardo', 'Khaki', 2010);
insert into cars (id, model, color, release_year) values (182, 'Galant', 'Pink', 1994);
insert into cars (id, model, color, release_year) values (183, 'E-Class', 'Maroon', 1994);
insert into cars (id, model, color, release_year) values (184, 'X3', 'Turquoise', 2012);
insert into cars (id, model, color, release_year) values (185, 'Elantra', 'Turquoise', 2003);
insert into cars (id, model, color, release_year) values (186, 'Express 1500', 'Khaki', 1996);
insert into cars (id, model, color, release_year) values (187, 'Q7', 'Crimson', 2007);
insert into cars (id, model, color, release_year) values (188, '900', 'Crimson', 1995);
insert into cars (id, model, color, release_year) values (189, 'Ram Wagon B150', 'Khaki', 1993);
insert into cars (id, model, color, release_year) values (190, 'Firefly', 'Turquoise', 1988);
insert into cars (id, model, color, release_year) values (191, 'H1', 'Teal', 2004);
insert into cars (id, model, color, release_year) values (192, 'Pathfinder', 'Pink', 2004);
insert into cars (id, model, color, release_year) values (193, 'S60', 'Purple', 2011);
insert into cars (id, model, color, release_year) values (194, 'Ram 3500', 'Orange', 2005);
insert into cars (id, model, color, release_year) values (195, 'Titan', 'Turquoise', 2004);
insert into cars (id, model, color, release_year) values (196, 'Silhouette', 'Maroon', 1993);
insert into cars (id, model, color, release_year) values (197, 'Custom Cruiser', 'Orange', 1992);
insert into cars (id, model, color, release_year) values (198, 'F250', 'Puce', 1994);
insert into cars (id, model, color, release_year) values (199, 'Tribute', 'Maroon', 2006);
insert into cars (id, model, color, release_year) values (200, 'Sable', 'Turquoise', 2000);
insert into cars (id, model, color, release_year) values (201, 'S10 Blazer', 'Teal', 1994);
insert into cars (id, model, color, release_year) values (202, 'Truck', 'Turquoise', 1993);
insert into cars (id, model, color, release_year) values (203, 'Capri', 'Green', 1994);
insert into cars (id, model, color, release_year) values (204, 'Continental', 'Pink', 2006);
insert into cars (id, model, color, release_year) values (205, 'Club Wagon', 'Purple', 1996);
insert into cars (id, model, color, release_year) values (206, 'Crossfire', 'Indigo', 2004);
insert into cars (id, model, color, release_year) values (207, 'Century', 'Aquamarine', 1987);
insert into cars (id, model, color, release_year) values (208, 'Blazer', 'Aquamarine', 2005);
insert into cars (id, model, color, release_year) values (209, 'Savana 1500', 'Indigo', 2000);
insert into cars (id, model, color, release_year) values (210, 'RAV4', 'Turquoise', 2012);
insert into cars (id, model, color, release_year) values (211, 'Intrigue', 'Aquamarine', 2001);
insert into cars (id, model, color, release_year) values (212, 'Maxima', 'Pink', 1996);
insert into cars (id, model, color, release_year) values (213, 'Arnage', 'Puce', 2008);
insert into cars (id, model, color, release_year) values (214, 'Countach', 'Indigo', 1985);
insert into cars (id, model, color, release_year) values (215, 'Chariot', 'Pink', 1989);
insert into cars (id, model, color, release_year) values (216, 'Mountaineer', 'Blue', 1997);
insert into cars (id, model, color, release_year) values (217, 'Passat', 'Indigo', 2012);
insert into cars (id, model, color, release_year) values (218, 'del Sol', 'Teal', 1994);
insert into cars (id, model, color, release_year) values (219, 'MKZ', 'Pink', 2012);
insert into cars (id, model, color, release_year) values (220, 'Viper', 'Mauv', 2010);
insert into cars (id, model, color, release_year) values (221, 'New Beetle', 'Purple', 2012);
insert into cars (id, model, color, release_year) values (222, 'CT', 'Red', 2012);
insert into cars (id, model, color, release_year) values (223, 'E-Series', 'Crimson', 1994);
insert into cars (id, model, color, release_year) values (224, 'Wrangler', 'Orange', 2006);
insert into cars (id, model, color, release_year) values (225, 'Mustang', 'Orange', 2010);
insert into cars (id, model, color, release_year) values (226, 'APV', 'Orange', 1992);
insert into cars (id, model, color, release_year) values (227, 'Ranger', 'Pink', 2009);
insert into cars (id, model, color, release_year) values (228, '90', 'Orange', 1990);
insert into cars (id, model, color, release_year) values (229, 'Mystique', 'Teal', 1997);
insert into cars (id, model, color, release_year) values (230, '9-5', 'Orange', 2003);
insert into cars (id, model, color, release_year) values (231, '6000', 'Purple', 1984);
insert into cars (id, model, color, release_year) values (232, 'SJ', 'Violet', 1992);
insert into cars (id, model, color, release_year) values (233, '7 Series', 'Blue', 2011);
insert into cars (id, model, color, release_year) values (234, 'Phaeton', 'Maroon', 2006);
insert into cars (id, model, color, release_year) values (235, 'Sidekick', 'Green', 1991);
insert into cars (id, model, color, release_year) values (236, 'Elantra', 'Indigo', 2010);
insert into cars (id, model, color, release_year) values (237, 'MX-6', 'Pink', 1990);
insert into cars (id, model, color, release_year) values (238, 'SVX', 'Orange', 1996);
insert into cars (id, model, color, release_year) values (239, '9-5', 'Aquamarine', 2005);
insert into cars (id, model, color, release_year) values (240, 'DB9', 'Purple', 2007);
insert into cars (id, model, color, release_year) values (241, 'Z8', 'Teal', 2003);
insert into cars (id, model, color, release_year) values (242, 'Biturbo', 'Pink', 1987);
insert into cars (id, model, color, release_year) values (243, 'XL-7', 'Aquamarine', 2006);
insert into cars (id, model, color, release_year) values (244, 'Viper RT/10', 'Indigo', 1994);
insert into cars (id, model, color, release_year) values (245, 'C-Class', 'Khaki', 2007);
insert into cars (id, model, color, release_year) values (246, 'Alpina B7', 'Maroon', 2007);
insert into cars (id, model, color, release_year) values (247, 'Century', 'Puce', 1986);
insert into cars (id, model, color, release_year) values (248, 'Scirocco', 'Crimson', 1987);
insert into cars (id, model, color, release_year) values (249, 'Grand Marquis', 'Blue', 1992);
insert into cars (id, model, color, release_year) values (250, 'DeVille', 'Violet', 1997);
insert into cars (id, model, color, release_year) values (251, 'Continental GTC', 'Aquamarine', 2011);
insert into cars (id, model, color, release_year) values (252, 'Fit', 'Goldenrod', 2008);
insert into cars (id, model, color, release_year) values (253, 'M5', 'Blue', 2008);
insert into cars (id, model, color, release_year) values (254, 'Xterra', 'Purple', 2000);
insert into cars (id, model, color, release_year) values (255, 'S4', 'Goldenrod', 2008);
insert into cars (id, model, color, release_year) values (256, '9000', 'Red', 1988);
insert into cars (id, model, color, release_year) values (257, 'E250', 'Turquoise', 1984);
insert into cars (id, model, color, release_year) values (258, 'Ranger', 'Goldenrod', 1992);
insert into cars (id, model, color, release_year) values (259, 'XK Series', 'Yellow', 2001);
insert into cars (id, model, color, release_year) values (260, 'LR3', 'Turquoise', 2008);
insert into cars (id, model, color, release_year) values (261, 'Aspen', 'Teal', 1976);
insert into cars (id, model, color, release_year) values (262, 'Grand Cherokee', 'Khaki', 1999);
insert into cars (id, model, color, release_year) values (263, 'CR-V', 'Violet', 2009);
insert into cars (id, model, color, release_year) values (264, 'Camaro', 'Yellow', 1970);
insert into cars (id, model, color, release_year) values (265, 'S10', 'Mauv', 1994);
insert into cars (id, model, color, release_year) values (266, 'Starion', 'Indigo', 1986);
insert into cars (id, model, color, release_year) values (267, 'Express 2500', 'Red', 2002);
insert into cars (id, model, color, release_year) values (268, 'Amanti', 'Indigo', 2005);
insert into cars (id, model, color, release_year) values (269, '900', 'Goldenrod', 1987);
insert into cars (id, model, color, release_year) values (270, 'Contour', 'Fuscia', 1995);
insert into cars (id, model, color, release_year) values (271, 'Continental Flying Spur', 'Indigo', 2012);
insert into cars (id, model, color, release_year) values (272, 'CL-Class', 'Maroon', 2012);
insert into cars (id, model, color, release_year) values (273, 'Astro', 'Maroon', 1992);
insert into cars (id, model, color, release_year) values (274, 'Eos', 'Purple', 2010);
insert into cars (id, model, color, release_year) values (275, 'Ram Van 1500', 'Purple', 1998);
insert into cars (id, model, color, release_year) values (276, 'Escalade EXT', 'Turquoise', 2005);
insert into cars (id, model, color, release_year) values (277, 'CLK-Class', 'Teal', 2009);
insert into cars (id, model, color, release_year) values (278, 'CLK-Class', 'Orange', 2009);
insert into cars (id, model, color, release_year) values (279, 'Landaulet', 'Teal', 2012);
insert into cars (id, model, color, release_year) values (280, '760', 'Khaki', 2004);
insert into cars (id, model, color, release_year) values (281, 'LeMans', 'Indigo', 1990);
insert into cars (id, model, color, release_year) values (282, 'Escalade EXT', 'Violet', 2012);
insert into cars (id, model, color, release_year) values (283, 'T100', 'Aquamarine', 1994);
insert into cars (id, model, color, release_year) values (284, 'Reatta', 'Crimson', 1991);
insert into cars (id, model, color, release_year) values (285, 'Grand Am', 'Teal', 2000);
insert into cars (id, model, color, release_year) values (286, 'E150', 'Green', 2006);
insert into cars (id, model, color, release_year) values (287, 'RX', 'Maroon', 2011);
insert into cars (id, model, color, release_year) values (288, 'Esprit', 'Mauv', 1990);
insert into cars (id, model, color, release_year) values (289, 'A4', 'Aquamarine', 2009);
insert into cars (id, model, color, release_year) values (290, 'LS', 'Mauv', 1999);
insert into cars (id, model, color, release_year) values (291, 'Mark LT', 'Goldenrod', 2006);
insert into cars (id, model, color, release_year) values (292, 'Savana 2500', 'Fuscia', 2010);
insert into cars (id, model, color, release_year) values (293, 'MX-5', 'Teal', 2008);
insert into cars (id, model, color, release_year) values (294, 'Caravan', 'Mauv', 2000);
insert into cars (id, model, color, release_year) values (295, 'Mirage', 'Indigo', 1984);
insert into cars (id, model, color, release_year) values (296, 'Skyhawk', 'Green', 1989);
insert into cars (id, model, color, release_year) values (297, 'Pathfinder', 'Turquoise', 2006);
insert into cars (id, model, color, release_year) values (298, 'Ram Van 3500', 'Purple', 1996);
insert into cars (id, model, color, release_year) values (299, 'F430 Spider', 'Aquamarine', 2006);
insert into cars (id, model, color, release_year) values (300, 'Cougar', 'Orange', 1986);
insert into cars (id, model, color, release_year) values (301, 'Civic Si', 'Indigo', 2003);
insert into cars (id, model, color, release_year) values (302, 'V8', 'Indigo', 1991);
insert into cars (id, model, color, release_year) values (303, 'Montana', 'Pink', 2006);
insert into cars (id, model, color, release_year) values (304, 'Passat', 'Green', 2003);
insert into cars (id, model, color, release_year) values (305, 'Firebird', 'Orange', 1997);
insert into cars (id, model, color, release_year) values (306, 'Grand Marquis', 'Indigo', 2007);
insert into cars (id, model, color, release_year) values (307, '599 GTB Fiorano', 'Purple', 2010);
insert into cars (id, model, color, release_year) values (308, 'Accent', 'Khaki', 2006);
insert into cars (id, model, color, release_year) values (309, 'Lightning', 'Pink', 1994);
insert into cars (id, model, color, release_year) values (310, '7 Series', 'Blue', 1992);
insert into cars (id, model, color, release_year) values (311, 'Chariot', 'Green', 1986);
insert into cars (id, model, color, release_year) values (312, 'Mark VIII', 'Purple', 1998);
insert into cars (id, model, color, release_year) values (313, 'Alpina B7', 'Pink', 2008);
insert into cars (id, model, color, release_year) values (314, '911', 'Crimson', 1989);
insert into cars (id, model, color, release_year) values (315, 'Magnum', 'Violet', 2005);
insert into cars (id, model, color, release_year) values (316, 'Sonoma Club', 'Crimson', 1992);
insert into cars (id, model, color, release_year) values (317, 'Dakota Club', 'Orange', 1997);
insert into cars (id, model, color, release_year) values (318, 'A8', 'Green', 2010);
insert into cars (id, model, color, release_year) values (319, 'RX', 'Blue', 2002);
insert into cars (id, model, color, release_year) values (320, 'X-Type', 'Pink', 2004);
insert into cars (id, model, color, release_year) values (321, 'V8', 'Teal', 1994);
insert into cars (id, model, color, release_year) values (322, 'Laser', 'Crimson', 1985);
insert into cars (id, model, color, release_year) values (323, 'Bonneville', 'Violet', 1968);
insert into cars (id, model, color, release_year) values (324, 'F-Series', 'Turquoise', 1988);
insert into cars (id, model, color, release_year) values (325, 'SRX', 'Maroon', 2009);
insert into cars (id, model, color, release_year) values (326, 'Supra', 'Red', 1998);
insert into cars (id, model, color, release_year) values (327, '5 Series', 'Orange', 2011);
insert into cars (id, model, color, release_year) values (328, 'Landaulet', 'Crimson', 2009);
insert into cars (id, model, color, release_year) values (329, 'Prelude', 'Aquamarine', 1986);
insert into cars (id, model, color, release_year) values (330, 'SLX', 'Blue', 1997);
insert into cars (id, model, color, release_year) values (331, 'Liberty', 'Green', 2009);
insert into cars (id, model, color, release_year) values (332, 'Eurovan', 'Goldenrod', 2003);
insert into cars (id, model, color, release_year) values (333, 'Z8', 'Pink', 2003);
insert into cars (id, model, color, release_year) values (334, 'Focus', 'Violet', 2009);
insert into cars (id, model, color, release_year) values (335, 'Golf', 'Mauv', 2003);
insert into cars (id, model, color, release_year) values (336, '430 Scuderia', 'Khaki', 2009);
insert into cars (id, model, color, release_year) values (337, 'A6', 'Teal', 2004);
insert into cars (id, model, color, release_year) values (338, 'Murano', 'Puce', 2005);
insert into cars (id, model, color, release_year) values (339, 'Seville', 'Blue', 1995);
insert into cars (id, model, color, release_year) values (340, '5 Series', 'Puce', 2002);
insert into cars (id, model, color, release_year) values (341, 'Avalanche 2500', 'Fuscia', 2006);
insert into cars (id, model, color, release_year) values (342, 'Starion', 'Turquoise', 1987);
insert into cars (id, model, color, release_year) values (343, 'Accord', 'Teal', 1997);
insert into cars (id, model, color, release_year) values (344, 'Cordia', 'Green', 1985);
insert into cars (id, model, color, release_year) values (345, 'XK Series', 'Fuscia', 2003);
insert into cars (id, model, color, release_year) values (346, 'Terrain', 'Teal', 2012);
insert into cars (id, model, color, release_year) values (347, 'Countryman', 'Teal', 2011);
insert into cars (id, model, color, release_year) values (348, 'A4', 'Indigo', 2000);
insert into cars (id, model, color, release_year) values (349, 'IS', 'Fuscia', 2001);
insert into cars (id, model, color, release_year) values (350, 'C-Class', 'Red', 1996);
insert into cars (id, model, color, release_year) values (351, 'MDX', 'Mauv', 2008);
insert into cars (id, model, color, release_year) values (352, '929', 'Khaki', 1992);
insert into cars (id, model, color, release_year) values (353, 'Colorado', 'Purple', 2009);
insert into cars (id, model, color, release_year) values (354, 'Familia', 'Khaki', 1991);
insert into cars (id, model, color, release_year) values (355, 'Grand Am', 'Indigo', 2000);
insert into cars (id, model, color, release_year) values (356, 'Civic Si', 'Red', 2003);
insert into cars (id, model, color, release_year) values (357, 'Pilot', 'Yellow', 2005);
insert into cars (id, model, color, release_year) values (358, 'GTI', 'Fuscia', 2007);
insert into cars (id, model, color, release_year) values (359, 'Trooper', 'Turquoise', 2002);
insert into cars (id, model, color, release_year) values (360, 'Equator', 'Puce', 2010);
insert into cars (id, model, color, release_year) values (361, 'Mustang', 'Blue', 1968);
insert into cars (id, model, color, release_year) values (362, 'Coachbuilder', 'Mauv', 1991);
insert into cars (id, model, color, release_year) values (363, 'Carens', 'Maroon', 2008);
insert into cars (id, model, color, release_year) values (364, 'Express 1500', 'Yellow', 2003);
insert into cars (id, model, color, release_year) values (365, 'RVR', 'Orange', 1993);
insert into cars (id, model, color, release_year) values (366, 'Versa', 'Pink', 2010);
insert into cars (id, model, color, release_year) values (367, 'Mark VIII', 'Yellow', 1994);
insert into cars (id, model, color, release_year) values (368, 'Ram 1500', 'Mauv', 1997);
insert into cars (id, model, color, release_year) values (369, 'Grand Caravan', 'Crimson', 2011);
insert into cars (id, model, color, release_year) values (370, 'X3', 'Violet', 2004);
insert into cars (id, model, color, release_year) values (371, 'Boxster', 'Blue', 2003);
insert into cars (id, model, color, release_year) values (372, 'Quest', 'Mauv', 2011);
insert into cars (id, model, color, release_year) values (373, 'F250', 'Yellow', 1992);
insert into cars (id, model, color, release_year) values (374, 'Sierra 2500', 'Puce', 2007);
insert into cars (id, model, color, release_year) values (375, 'Traverse', 'Crimson', 2010);
insert into cars (id, model, color, release_year) values (376, 'Ram 2500', 'Turquoise', 2002);
insert into cars (id, model, color, release_year) values (377, '2500 Club Coupe', 'Turquoise', 1996);
insert into cars (id, model, color, release_year) values (378, 'LeMans', 'Green', 1968);
insert into cars (id, model, color, release_year) values (379, 'F350', 'Red', 2000);
insert into cars (id, model, color, release_year) values (380, 'Previa', 'Puce', 1991);
insert into cars (id, model, color, release_year) values (381, 'LeSabre', 'Blue', 1998);
insert into cars (id, model, color, release_year) values (382, 'Aspen', 'Maroon', 1976);
insert into cars (id, model, color, release_year) values (383, 'Grand Prix', 'Mauv', 1997);
insert into cars (id, model, color, release_year) values (384, 'Villager', 'Blue', 1996);
insert into cars (id, model, color, release_year) values (385, 'S80', 'Yellow', 2007);
insert into cars (id, model, color, release_year) values (386, 'Sunbird', 'Fuscia', 1991);
insert into cars (id, model, color, release_year) values (387, 'M-Class', 'Green', 2002);
insert into cars (id, model, color, release_year) values (388, 'Thunderbird', 'Indigo', 1992);
insert into cars (id, model, color, release_year) values (389, 'Grand Am', 'Maroon', 1988);
insert into cars (id, model, color, release_year) values (390, 'LX', 'Puce', 2011);
insert into cars (id, model, color, release_year) values (391, 'Q7', 'Mauv', 2009);
insert into cars (id, model, color, release_year) values (392, 'Accent', 'Turquoise', 1997);
insert into cars (id, model, color, release_year) values (393, 'Wrangler', 'Blue', 2003);
insert into cars (id, model, color, release_year) values (394, 'Passat', 'Goldenrod', 2005);
insert into cars (id, model, color, release_year) values (395, 'XL7', 'Khaki', 2008);
insert into cars (id, model, color, release_year) values (396, 'Coupe GT', 'Orange', 1987);
insert into cars (id, model, color, release_year) values (397, 'FJ Cruiser', 'Goldenrod', 2010);
insert into cars (id, model, color, release_year) values (398, 'Grand Marquis', 'Yellow', 1994);
insert into cars (id, model, color, release_year) values (399, 'Quest', 'Maroon', 1997);
insert into cars (id, model, color, release_year) values (400, 'TT', 'Aquamarine', 2009);
insert into cars (id, model, color, release_year) values (401, 'CR-Z', 'Crimson', 2012);
insert into cars (id, model, color, release_year) values (402, 'Accord', 'Pink', 1983);
insert into cars (id, model, color, release_year) values (403, 'CL-Class', 'Indigo', 2012);
insert into cars (id, model, color, release_year) values (404, 'Malibu', 'Turquoise', 2007);
insert into cars (id, model, color, release_year) values (405, 'Century', 'Violet', 1993);
insert into cars (id, model, color, release_year) values (406, 'Blazer', 'Pink', 1997);
insert into cars (id, model, color, release_year) values (407, '350Z', 'Blue', 2007);
insert into cars (id, model, color, release_year) values (408, 'MKX', 'Orange', 2012);
insert into cars (id, model, color, release_year) values (409, 'C-Class', 'Indigo', 1996);
insert into cars (id, model, color, release_year) values (410, 'Leganza', 'Pink', 2002);
insert into cars (id, model, color, release_year) values (411, 'Discovery', 'Blue', 2005);
insert into cars (id, model, color, release_year) values (412, 'Cube', 'Green', 2009);
insert into cars (id, model, color, release_year) values (413, 'S8', 'Maroon', 2009);
insert into cars (id, model, color, release_year) values (414, 'Z4 M', 'Green', 2009);
insert into cars (id, model, color, release_year) values (415, 'Savana 1500', 'Pink', 2004);
insert into cars (id, model, color, release_year) values (416, 'Neon', 'Puce', 1995);
insert into cars (id, model, color, release_year) values (417, 'Camaro', 'Mauv', 1999);
insert into cars (id, model, color, release_year) values (418, 'LS Hybrid', 'Purple', 2010);
insert into cars (id, model, color, release_year) values (419, '600SEC', 'Purple', 1993);
insert into cars (id, model, color, release_year) values (420, 'LaCrosse', 'Mauv', 2008);
insert into cars (id, model, color, release_year) values (421, 'M-Class', 'Teal', 2009);
insert into cars (id, model, color, release_year) values (422, 'E-Series', 'Orange', 1990);
insert into cars (id, model, color, release_year) values (423, 'Trans Sport', 'Blue', 1996);
insert into cars (id, model, color, release_year) values (424, '325', 'Goldenrod', 2005);
insert into cars (id, model, color, release_year) values (425, 'Z8', 'Fuscia', 2003);
insert into cars (id, model, color, release_year) values (426, 'Vandura 1500', 'Puce', 1992);
insert into cars (id, model, color, release_year) values (427, 'SLS AMG', 'Fuscia', 2011);
insert into cars (id, model, color, release_year) values (428, 'Sonata', 'Yellow', 2000);
insert into cars (id, model, color, release_year) values (429, 'Sierra 2500', 'Orange', 2001);
insert into cars (id, model, color, release_year) values (430, 'Impreza', 'Fuscia', 2001);
insert into cars (id, model, color, release_year) values (431, 'Grand Marquis', 'Maroon', 1985);
insert into cars (id, model, color, release_year) values (432, 'Yukon XL 2500', 'Maroon', 2002);
insert into cars (id, model, color, release_year) values (433, 'Corvette', 'Yellow', 1962);
insert into cars (id, model, color, release_year) values (434, 'Ram Van 1500', 'Teal', 2003);
insert into cars (id, model, color, release_year) values (435, 'Grand Prix', 'Green', 1991);
insert into cars (id, model, color, release_year) values (436, 'Land Cruiser', 'Aquamarine', 1995);
insert into cars (id, model, color, release_year) values (437, 'GTI', 'Goldenrod', 2001);
insert into cars (id, model, color, release_year) values (438, 'Precis', 'Pink', 1990);
insert into cars (id, model, color, release_year) values (439, 'Five Hundred', 'Violet', 2007);
insert into cars (id, model, color, release_year) values (440, 'V8 Vantage', 'Aquamarine', 2011);
insert into cars (id, model, color, release_year) values (441, 'Pajero', 'Maroon', 2004);
insert into cars (id, model, color, release_year) values (442, 'Prelude', 'Aquamarine', 2001);
insert into cars (id, model, color, release_year) values (443, 'Gallardo', 'Indigo', 2010);
insert into cars (id, model, color, release_year) values (444, 'GLK-Class', 'Maroon', 2012);
insert into cars (id, model, color, release_year) values (445, 'Envoy', 'Purple', 1998);
insert into cars (id, model, color, release_year) values (446, 'Continental', 'Crimson', 2006);
insert into cars (id, model, color, release_year) values (447, 'Galant', 'Teal', 1998);
insert into cars (id, model, color, release_year) values (448, 'B-Series', 'Indigo', 1998);
insert into cars (id, model, color, release_year) values (449, 'Silverado 3500', 'Blue', 2012);
insert into cars (id, model, color, release_year) values (450, 'Thunderbird', 'Mauv', 1990);
insert into cars (id, model, color, release_year) values (451, 'Corvette', 'Indigo', 1998);
insert into cars (id, model, color, release_year) values (452, 'Protege', 'Yellow', 2002);
insert into cars (id, model, color, release_year) values (453, 'Quest', 'Teal', 1999);
insert into cars (id, model, color, release_year) values (454, 'Vibe', 'Green', 2003);
insert into cars (id, model, color, release_year) values (455, 'Veloster', 'Teal', 2013);
insert into cars (id, model, color, release_year) values (456, '1500', 'Maroon', 1992);
insert into cars (id, model, color, release_year) values (457, 'Caliber', 'Aquamarine', 2010);
insert into cars (id, model, color, release_year) values (458, 'Grand Cherokee', 'Maroon', 2010);
insert into cars (id, model, color, release_year) values (459, 'T100 Xtra', 'Green', 1997);
insert into cars (id, model, color, release_year) values (460, 'Grand Cherokee', 'Khaki', 2001);
insert into cars (id, model, color, release_year) values (461, '600', 'Red', 1958);
insert into cars (id, model, color, release_year) values (462, 'Sequoia', 'Pink', 2011);
insert into cars (id, model, color, release_year) values (463, 'VUE', 'Violet', 2008);
insert into cars (id, model, color, release_year) values (464, 'Silhouette', 'Yellow', 2002);
insert into cars (id, model, color, release_year) values (465, 'Mark LT', 'Fuscia', 2008);
insert into cars (id, model, color, release_year) values (466, 'Outlook', 'Green', 2008);
insert into cars (id, model, color, release_year) values (467, 'F350', 'Purple', 2001);
insert into cars (id, model, color, release_year) values (468, 'Coupe', 'Fuscia', 2005);
insert into cars (id, model, color, release_year) values (469, 'Acclaim', 'Aquamarine', 1993);
insert into cars (id, model, color, release_year) values (470, 'Amanti', 'Yellow', 2006);
insert into cars (id, model, color, release_year) values (471, 'E-Class', 'Khaki', 2007);
insert into cars (id, model, color, release_year) values (472, 'Prowler', 'Violet', 2001);
insert into cars (id, model, color, release_year) values (473, 'Expedition', 'Indigo', 2012);
insert into cars (id, model, color, release_year) values (474, 'Yukon', 'Turquoise', 2003);
insert into cars (id, model, color, release_year) values (475, 'Passport', 'Pink', 1997);
insert into cars (id, model, color, release_year) values (476, 'C-Class', 'Pink', 1994);
insert into cars (id, model, color, release_year) values (477, 'Civic', 'Goldenrod', 1999);
insert into cars (id, model, color, release_year) values (478, 'Jimmy', 'Indigo', 2000);
insert into cars (id, model, color, release_year) values (479, 'Astro', 'Turquoise', 1993);
insert into cars (id, model, color, release_year) values (480, 'Taurus', 'Crimson', 1992);
insert into cars (id, model, color, release_year) values (481, 'S6', 'Orange', 2011);
insert into cars (id, model, color, release_year) values (482, 'GS', 'Khaki', 1998);
insert into cars (id, model, color, release_year) values (483, 'Defender', 'Indigo', 1993);
insert into cars (id, model, color, release_year) values (484, 'Rendezvous', 'Purple', 2006);
insert into cars (id, model, color, release_year) values (485, 'Expedition', 'Orange', 1997);
insert into cars (id, model, color, release_year) values (486, 'CLS-Class', 'Pink', 2008);
insert into cars (id, model, color, release_year) values (487, 'Cayenne', 'Blue', 2011);
insert into cars (id, model, color, release_year) values (488, 'RAV4', 'Mauv', 1997);
insert into cars (id, model, color, release_year) values (489, 'Achieva', 'Goldenrod', 1993);
insert into cars (id, model, color, release_year) values (490, 'Monte Carlo', 'Yellow', 2004);
insert into cars (id, model, color, release_year) values (491, 'Tiburon', 'Purple', 2009);
insert into cars (id, model, color, release_year) values (492, 'Savana 3500', 'Turquoise', 2007);
insert into cars (id, model, color, release_year) values (493, 'H1', 'Turquoise', 2001);
insert into cars (id, model, color, release_year) values (494, 'Jimmy', 'Maroon', 1998);
insert into cars (id, model, color, release_year) values (495, 'Express 3500', 'Goldenrod', 2008);
insert into cars (id, model, color, release_year) values (496, 'TT', 'Maroon', 2011);
insert into cars (id, model, color, release_year) values (497, 'Edge', 'Fuscia', 2008);
insert into cars (id, model, color, release_year) values (498, 'GT-R', 'Crimson', 2013);
insert into cars (id, model, color, release_year) values (499, 'DBS', 'Crimson', 2009);
insert into cars (id, model, color, release_year) values (500, 'Eos', 'Red', 2012);
insert into cars (id, model, color, release_year) values (501, 'Montero', 'Maroon', 2002);
insert into cars (id, model, color, release_year) values (502, 'i-290', 'Turquoise', 2007);
insert into cars (id, model, color, release_year) values (503, 'Jetta', 'Red', 2002);
insert into cars (id, model, color, release_year) values (504, 'Titan', 'Pink', 2010);
insert into cars (id, model, color, release_year) values (505, 'Tahoe', 'Blue', 1999);
insert into cars (id, model, color, release_year) values (506, 'G', 'Yellow', 2007);
insert into cars (id, model, color, release_year) values (507, 'F-Series', 'Yellow', 2005);
insert into cars (id, model, color, release_year) values (508, 'Dakota Club', 'Goldenrod', 2002);
insert into cars (id, model, color, release_year) values (509, 'Silverado 2500', 'Yellow', 2009);
insert into cars (id, model, color, release_year) values (510, 'Starion', 'Indigo', 1984);
insert into cars (id, model, color, release_year) values (511, 'Cabriolet', 'Mauv', 1999);
insert into cars (id, model, color, release_year) values (512, 'LTD', 'Indigo', 1985);
insert into cars (id, model, color, release_year) values (513, 'Avalon', 'Aquamarine', 2009);
insert into cars (id, model, color, release_year) values (514, 'Explorer Sport', 'Indigo', 2003);
insert into cars (id, model, color, release_year) values (515, 'Z4', 'Green', 2012);
insert into cars (id, model, color, release_year) values (516, 'Range Rover', 'Red', 1993);
insert into cars (id, model, color, release_year) values (517, 'Express 3500', 'Pink', 2000);
insert into cars (id, model, color, release_year) values (518, 'Truck', 'Maroon', 1994);
insert into cars (id, model, color, release_year) values (519, 'CX-9', 'Khaki', 2010);
insert into cars (id, model, color, release_year) values (520, '1500 Club Coupe', 'Turquoise', 1992);
insert into cars (id, model, color, release_year) values (521, 'A6', 'Red', 2005);
insert into cars (id, model, color, release_year) values (522, 'Arnage', 'Fuscia', 2007);
insert into cars (id, model, color, release_year) values (523, 'Thunderbird', 'Orange', 1995);
insert into cars (id, model, color, release_year) values (524, 'Vandura 3500', 'Purple', 1993);
insert into cars (id, model, color, release_year) values (525, 'Boxster', 'Orange', 1997);
insert into cars (id, model, color, release_year) values (526, 'S2000', 'Violet', 2008);
insert into cars (id, model, color, release_year) values (527, 'MX-6', 'Indigo', 1996);
insert into cars (id, model, color, release_year) values (528, 'Acadia', 'Green', 2010);
insert into cars (id, model, color, release_year) values (529, 'Th!nk', 'Aquamarine', 2000);
insert into cars (id, model, color, release_year) values (530, 'Camry', 'Aquamarine', 2001);
insert into cars (id, model, color, release_year) values (531, 'GTI', 'Turquoise', 1986);
insert into cars (id, model, color, release_year) values (532, 'Protege', 'Orange', 1994);
insert into cars (id, model, color, release_year) values (533, 'Outback', 'Violet', 2010);
insert into cars (id, model, color, release_year) values (534, 'Legacy', 'Crimson', 1999);
insert into cars (id, model, color, release_year) values (535, 'S40', 'Goldenrod', 2000);
insert into cars (id, model, color, release_year) values (536, 'Sierra 3500', 'Turquoise', 2011);
insert into cars (id, model, color, release_year) values (537, 'LR2', 'Mauv', 2010);
insert into cars (id, model, color, release_year) values (538, 'Sidekick', 'Green', 1989);
insert into cars (id, model, color, release_year) values (539, 'Millenia', 'Blue', 2000);
insert into cars (id, model, color, release_year) values (540, 'MKX', 'Indigo', 2012);
insert into cars (id, model, color, release_year) values (541, '5 Series', 'Goldenrod', 2004);
insert into cars (id, model, color, release_year) values (542, 'Forester', 'Mauv', 2000);
insert into cars (id, model, color, release_year) values (543, 'Grand Prix', 'Khaki', 2000);
insert into cars (id, model, color, release_year) values (544, '3500', 'Turquoise', 1998);
insert into cars (id, model, color, release_year) values (545, 'Camry Hybrid', 'Puce', 2010);
insert into cars (id, model, color, release_year) values (546, 'V40', 'Violet', 2001);
insert into cars (id, model, color, release_year) values (547, 'Grand Marquis', 'Purple', 2000);
insert into cars (id, model, color, release_year) values (548, 'F250', 'Turquoise', 1995);
insert into cars (id, model, color, release_year) values (549, 'Safari', 'Puce', 2000);
insert into cars (id, model, color, release_year) values (550, 'Pajero', 'Red', 2001);
insert into cars (id, model, color, release_year) values (551, 'GS', 'Teal', 2009);
insert into cars (id, model, color, release_year) values (552, 'Exige', 'Fuscia', 2012);
insert into cars (id, model, color, release_year) values (553, 'Continental GTC', 'Fuscia', 2009);
insert into cars (id, model, color, release_year) values (554, 'Firefly', 'Crimson', 1995);
insert into cars (id, model, color, release_year) values (555, 'Avenger', 'Aquamarine', 1999);
insert into cars (id, model, color, release_year) values (556, 'Silverado 3500', 'Goldenrod', 2007);
insert into cars (id, model, color, release_year) values (557, 'Borrego', 'Aquamarine', 2009);
insert into cars (id, model, color, release_year) values (558, 'S-Class', 'Puce', 2011);
insert into cars (id, model, color, release_year) values (559, 'Charger', 'Puce', 2011);
insert into cars (id, model, color, release_year) values (560, 'G-Class', 'Puce', 2012);
insert into cars (id, model, color, release_year) values (561, 'Yaris', 'Aquamarine', 2009);
insert into cars (id, model, color, release_year) values (562, 'F-250 Super Duty', 'Red', 2006);
insert into cars (id, model, color, release_year) values (563, 'Civic', 'Fuscia', 2010);
insert into cars (id, model, color, release_year) values (564, 'Grand Prix', 'Violet', 1998);
insert into cars (id, model, color, release_year) values (565, 'Scirocco', 'Khaki', 1987);
insert into cars (id, model, color, release_year) values (566, 'Previa', 'Green', 1995);
insert into cars (id, model, color, release_year) values (567, 'F250', 'Crimson', 1997);
insert into cars (id, model, color, release_year) values (568, 'Challenger', 'Puce', 2002);
insert into cars (id, model, color, release_year) values (569, 'Montero', 'Indigo', 1995);
insert into cars (id, model, color, release_year) values (570, '1500', 'Orange', 1995);
insert into cars (id, model, color, release_year) values (571, 'Legacy', 'Pink', 2000);
insert into cars (id, model, color, release_year) values (572, 'LS', 'Goldenrod', 2007);
insert into cars (id, model, color, release_year) values (573, 'Edge', 'Orange', 2008);
insert into cars (id, model, color, release_year) values (574, 'Jetta', 'Violet', 1990);
insert into cars (id, model, color, release_year) values (575, 'RX-7', 'Orange', 1994);
insert into cars (id, model, color, release_year) values (576, 'Freelander', 'Blue', 2005);
insert into cars (id, model, color, release_year) values (577, 'Crown Victoria', 'Crimson', 2006);
insert into cars (id, model, color, release_year) values (578, 'Mountaineer', 'Fuscia', 1997);
insert into cars (id, model, color, release_year) values (579, 'Durango', 'Goldenrod', 2011);
insert into cars (id, model, color, release_year) values (580, 'Aveo', 'Goldenrod', 2008);
insert into cars (id, model, color, release_year) values (581, 'S80', 'Green', 2003);
insert into cars (id, model, color, release_year) values (582, 'Odyssey', 'Mauv', 1995);
insert into cars (id, model, color, release_year) values (583, 'Terrain', 'Blue', 2012);
insert into cars (id, model, color, release_year) values (584, 'Cabriolet', 'Khaki', 1995);
insert into cars (id, model, color, release_year) values (585, 'Ghost', 'Aquamarine', 2011);
insert into cars (id, model, color, release_year) values (586, 'Civic', 'Mauv', 2000);
insert into cars (id, model, color, release_year) values (587, 'Voyager', 'Goldenrod', 1985);
insert into cars (id, model, color, release_year) values (588, 'LTD', 'Violet', 1985);
insert into cars (id, model, color, release_year) values (589, 'Galant', 'Crimson', 2004);
insert into cars (id, model, color, release_year) values (590, 'Coachbuilder', 'Indigo', 1995);
insert into cars (id, model, color, release_year) values (591, 'Viper', 'Fuscia', 1996);
insert into cars (id, model, color, release_year) values (592, 'Challenger', 'Pink', 1999);
insert into cars (id, model, color, release_year) values (593, 'Silverado 3500', 'Goldenrod', 2004);
insert into cars (id, model, color, release_year) values (594, 'GS', 'Turquoise', 1993);
insert into cars (id, model, color, release_year) values (595, 'TundraMax', 'Teal', 2008);
insert into cars (id, model, color, release_year) values (596, 'Aerio', 'Maroon', 2004);
insert into cars (id, model, color, release_year) values (597, 'XC70', 'Aquamarine', 2008);
insert into cars (id, model, color, release_year) values (598, 'X5', 'Violet', 2012);
insert into cars (id, model, color, release_year) values (599, 'Continental GT', 'Puce', 2009);
insert into cars (id, model, color, release_year) values (600, 'Navigator', 'Maroon', 2007);
insert into cars (id, model, color, release_year) values (601, 'Amanti', 'Khaki', 2007);
insert into cars (id, model, color, release_year) values (602, 'Vitara', 'Teal', 2004);
insert into cars (id, model, color, release_year) values (603, 'Lancer', 'Pink', 2008);
insert into cars (id, model, color, release_year) values (604, 'IS', 'Maroon', 2010);
insert into cars (id, model, color, release_year) values (605, 'Pajero', 'Puce', 2006);
insert into cars (id, model, color, release_year) values (606, 'Vanagon', 'Puce', 1984);
insert into cars (id, model, color, release_year) values (607, 'Esperante', 'Fuscia', 2006);
insert into cars (id, model, color, release_year) values (608, 'Probe', 'Maroon', 1995);
insert into cars (id, model, color, release_year) values (609, 'M', 'Red', 2008);
insert into cars (id, model, color, release_year) values (610, '940', 'Aquamarine', 1995);
insert into cars (id, model, color, release_year) values (611, 'Catera', 'Blue', 1999);
insert into cars (id, model, color, release_year) values (612, 'Jetta', 'Yellow', 2003);
insert into cars (id, model, color, release_year) values (613, '7 Series', 'Teal', 1999);
insert into cars (id, model, color, release_year) values (614, 'Grand Marquis', 'Indigo', 1986);
insert into cars (id, model, color, release_year) values (615, 'CR-V', 'Mauv', 2008);
insert into cars (id, model, color, release_year) values (616, 'Tacoma Xtra', 'Blue', 2002);
insert into cars (id, model, color, release_year) values (617, 'Bronco', 'Red', 1995);
insert into cars (id, model, color, release_year) values (618, 'i-350', 'Purple', 2006);
insert into cars (id, model, color, release_year) values (619, 'Q', 'Crimson', 2002);
insert into cars (id, model, color, release_year) values (620, 'CL65 AMG', 'Indigo', 2009);
insert into cars (id, model, color, release_year) values (621, 'Metro', 'Khaki', 1996);
insert into cars (id, model, color, release_year) values (622, 'Crown Victoria', 'Yellow', 2009);
insert into cars (id, model, color, release_year) values (623, 'Alero', 'Indigo', 1999);
insert into cars (id, model, color, release_year) values (624, 'Summit', 'Fuscia', 1992);
insert into cars (id, model, color, release_year) values (625, 'Legacy', 'Fuscia', 2004);
insert into cars (id, model, color, release_year) values (626, 'A3', 'Mauv', 2006);
insert into cars (id, model, color, release_year) values (627, 'Ram Wagon B150', 'Aquamarine', 1993);
insert into cars (id, model, color, release_year) values (628, '80', 'Teal', 1990);
insert into cars (id, model, color, release_year) values (629, 'Camaro', 'Violet', 1992);
insert into cars (id, model, color, release_year) values (630, 'Sunfire', 'Crimson', 2005);
insert into cars (id, model, color, release_year) values (631, 'Impala SS', 'Goldenrod', 1995);
insert into cars (id, model, color, release_year) values (632, 'Cougar', 'Fuscia', 1990);
insert into cars (id, model, color, release_year) values (633, '90', 'Aquamarine', 1988);
insert into cars (id, model, color, release_year) values (634, 'MX-5', 'Aquamarine', 1992);
insert into cars (id, model, color, release_year) values (635, 'Ram Van 1500', 'Green', 2003);
insert into cars (id, model, color, release_year) values (636, 'Quattroporte', 'Pink', 2010);
insert into cars (id, model, color, release_year) values (637, 'Sorento', 'Fuscia', 2003);
insert into cars (id, model, color, release_year) values (638, '7 Series', 'Indigo', 2002);
insert into cars (id, model, color, release_year) values (639, 'CC', 'Green', 2010);
insert into cars (id, model, color, release_year) values (640, 'S-Class', 'Pink', 1988);
insert into cars (id, model, color, release_year) values (641, 'Bronco', 'Violet', 1990);
insert into cars (id, model, color, release_year) values (642, 'Legacy', 'Maroon', 1995);
insert into cars (id, model, color, release_year) values (643, 'Firebird', 'Aquamarine', 2000);
insert into cars (id, model, color, release_year) values (644, 'Spyder', 'Red', 1989);
insert into cars (id, model, color, release_year) values (645, 'Eldorado', 'Red', 1993);
insert into cars (id, model, color, release_year) values (646, 'Tahoe', 'Teal', 2003);
insert into cars (id, model, color, release_year) values (647, 'Continental', 'Fuscia', 1992);
insert into cars (id, model, color, release_year) values (648, 'Silverado 3500', 'Orange', 2006);
insert into cars (id, model, color, release_year) values (649, 'Tribute', 'Blue', 2001);
insert into cars (id, model, color, release_year) values (650, '88', 'Turquoise', 1993);
insert into cars (id, model, color, release_year) values (651, 'Range Rover', 'Aquamarine', 1997);
insert into cars (id, model, color, release_year) values (652, 'CTS-V', 'Fuscia', 2007);
insert into cars (id, model, color, release_year) values (653, '9000', 'Green', 1998);
insert into cars (id, model, color, release_year) values (654, 'M', 'Pink', 2007);
insert into cars (id, model, color, release_year) values (655, 'Z4', 'Blue', 2011);
insert into cars (id, model, color, release_year) values (656, 'Safari', 'Mauv', 2002);
insert into cars (id, model, color, release_year) values (657, 'GTI', 'Green', 1987);
insert into cars (id, model, color, release_year) values (658, 'Thunderbird', 'Crimson', 1965);
insert into cars (id, model, color, release_year) values (659, 'S80', 'Violet', 2003);
insert into cars (id, model, color, release_year) values (660, 'xB', 'Goldenrod', 2010);
insert into cars (id, model, color, release_year) values (661, 'E350', 'Violet', 2008);
insert into cars (id, model, color, release_year) values (662, 'Lumina', 'Aquamarine', 1996);
insert into cars (id, model, color, release_year) values (663, 'Elise', 'Goldenrod', 2010);
insert into cars (id, model, color, release_year) values (664, 'Lancer', 'Aquamarine', 2004);
insert into cars (id, model, color, release_year) values (665, 'Achieva', 'Puce', 1995);
insert into cars (id, model, color, release_year) values (666, 'Celica', 'Fuscia', 1997);
insert into cars (id, model, color, release_year) values (667, '745', 'Purple', 2004);
insert into cars (id, model, color, release_year) values (668, 'J', 'Violet', 1997);
insert into cars (id, model, color, release_year) values (669, 'Suburban 2500', 'Puce', 1995);
insert into cars (id, model, color, release_year) values (670, 'Bonneville', 'Turquoise', 1987);
insert into cars (id, model, color, release_year) values (671, 'Grand Prix', 'Red', 1978);
insert into cars (id, model, color, release_year) values (672, 'Courier', 'Blue', 1986);
insert into cars (id, model, color, release_year) values (673, 'MKX', 'Mauv', 2010);
insert into cars (id, model, color, release_year) values (674, 'Suburban 2500', 'Purple', 1995);
insert into cars (id, model, color, release_year) values (675, 'B-Series Plus', 'Goldenrod', 2002);
insert into cars (id, model, color, release_year) values (676, 'Probe', 'Turquoise', 1995);
insert into cars (id, model, color, release_year) values (677, '944', 'Pink', 1987);
insert into cars (id, model, color, release_year) values (678, 'Forester', 'Yellow', 2010);
insert into cars (id, model, color, release_year) values (679, '1 Series', 'Indigo', 2009);
insert into cars (id, model, color, release_year) values (680, 'Avalon', 'Blue', 1996);
insert into cars (id, model, color, release_year) values (681, 'Legacy', 'Turquoise', 1989);
insert into cars (id, model, color, release_year) values (682, 'B-Series', 'Purple', 2008);
insert into cars (id, model, color, release_year) values (683, 'xB', 'Maroon', 2004);
insert into cars (id, model, color, release_year) values (684, 'Tempest', 'Mauv', 1967);
insert into cars (id, model, color, release_year) values (685, 'Frontier', 'Crimson', 2012);
insert into cars (id, model, color, release_year) values (686, 'Sierra 2500', 'Puce', 2012);
insert into cars (id, model, color, release_year) values (687, 'XJ', 'Turquoise', 2012);
insert into cars (id, model, color, release_year) values (688, 'Grand Marquis', 'Puce', 2001);
insert into cars (id, model, color, release_year) values (689, 'Blackwood', 'Green', 2003);
insert into cars (id, model, color, release_year) values (690, 'Navigator L', 'Crimson', 2010);
insert into cars (id, model, color, release_year) values (691, '88', 'Khaki', 1992);
insert into cars (id, model, color, release_year) values (692, 'VUE', 'Aquamarine', 2003);
insert into cars (id, model, color, release_year) values (693, '600', 'Goldenrod', 1959);
insert into cars (id, model, color, release_year) values (694, 'R-Class', 'Pink', 2007);
insert into cars (id, model, color, release_year) values (695, 'Landaulet', 'Maroon', 2012);
insert into cars (id, model, color, release_year) values (696, 'MDX', 'Purple', 2009);
insert into cars (id, model, color, release_year) values (697, 'G6', 'Goldenrod', 2008);
insert into cars (id, model, color, release_year) values (698, 'Escalade', 'Khaki', 1999);
insert into cars (id, model, color, release_year) values (699, 'Mazda6 Sport', 'Goldenrod', 2006);
insert into cars (id, model, color, release_year) values (700, 'Jetta', 'Maroon', 1998);
insert into cars (id, model, color, release_year) values (701, '98', 'Khaki', 1996);
insert into cars (id, model, color, release_year) values (702, 'New Beetle', 'Purple', 2005);
insert into cars (id, model, color, release_year) values (703, 'Express 2500', 'Indigo', 2000);
insert into cars (id, model, color, release_year) values (704, 'S4', 'Maroon', 2006);
insert into cars (id, model, color, release_year) values (705, 'DB9 Volante', 'Aquamarine', 2006);
insert into cars (id, model, color, release_year) values (706, 'S40', 'Violet', 2010);
insert into cars (id, model, color, release_year) values (707, 'Camry Hybrid', 'Indigo', 2007);
insert into cars (id, model, color, release_year) values (708, 'Accord', 'Maroon', 1986);
insert into cars (id, model, color, release_year) values (709, 'Eldorado', 'Orange', 1995);
insert into cars (id, model, color, release_year) values (710, 'RL', 'Green', 2002);
insert into cars (id, model, color, release_year) values (711, 'Accord', 'Blue', 1992);
insert into cars (id, model, color, release_year) values (712, 'Cobalt', 'Yellow', 2008);
insert into cars (id, model, color, release_year) values (713, 'Sprinter', 'Red', 2010);
insert into cars (id, model, color, release_year) values (714, 'Odyssey', 'Maroon', 2011);
insert into cars (id, model, color, release_year) values (715, 'Mustang', 'Turquoise', 2012);
insert into cars (id, model, color, release_year) values (716, 'Navigator L', 'Mauv', 2008);
insert into cars (id, model, color, release_year) values (717, 'Tundra', 'Purple', 2000);
insert into cars (id, model, color, release_year) values (718, 'Solstice', 'Pink', 2007);
insert into cars (id, model, color, release_year) values (719, 'RX', 'Maroon', 2006);
insert into cars (id, model, color, release_year) values (720, 'SC', 'Orange', 2004);
insert into cars (id, model, color, release_year) values (721, 'Avanti', 'Indigo', 1961);
insert into cars (id, model, color, release_year) values (722, 'CL-Class', 'Teal', 1999);
insert into cars (id, model, color, release_year) values (723, 'RVR', 'Purple', 1995);
insert into cars (id, model, color, release_year) values (724, 'L300', 'Red', 1990);
insert into cars (id, model, color, release_year) values (725, 'X5', 'Pink', 2002);
insert into cars (id, model, color, release_year) values (726, '928', 'Yellow', 1986);
insert into cars (id, model, color, release_year) values (727, 'Mystique', 'Indigo', 2000);
insert into cars (id, model, color, release_year) values (728, 'Montana SV6', 'Puce', 2006);
insert into cars (id, model, color, release_year) values (729, 'SJ 410', 'Khaki', 1986);
insert into cars (id, model, color, release_year) values (730, 'Quattroporte', 'Blue', 2012);
insert into cars (id, model, color, release_year) values (731, '2500', 'Fuscia', 1995);
insert into cars (id, model, color, release_year) values (732, 'Enclave', 'Indigo', 2009);
insert into cars (id, model, color, release_year) values (733, 'EX', 'Orange', 2010);
insert into cars (id, model, color, release_year) values (734, 'SLK-Class', 'Yellow', 2007);
insert into cars (id, model, color, release_year) values (735, 'Mazda3', 'Teal', 2005);
insert into cars (id, model, color, release_year) values (736, 'Sable', 'Red', 2003);
insert into cars (id, model, color, release_year) values (737, '600SEL', 'Khaki', 1992);
insert into cars (id, model, color, release_year) values (738, 'Corvette', 'Maroon', 1978);
insert into cars (id, model, color, release_year) values (739, 'TT', 'Fuscia', 2005);
insert into cars (id, model, color, release_year) values (740, 'LS Hybrid', 'Fuscia', 2010);
insert into cars (id, model, color, release_year) values (741, 'Grand Am', 'Pink', 1989);
insert into cars (id, model, color, release_year) values (742, 'Freestyle', 'Maroon', 2007);
insert into cars (id, model, color, release_year) values (743, 'Mazda5', 'Khaki', 2007);
insert into cars (id, model, color, release_year) values (744, 'CL65 AMG', 'Yellow', 2009);
insert into cars (id, model, color, release_year) values (745, 'S60', 'Goldenrod', 2001);
insert into cars (id, model, color, release_year) values (746, 'Sonata', 'Red', 2006);
insert into cars (id, model, color, release_year) values (747, 'Aero 8', 'Khaki', 2008);
insert into cars (id, model, color, release_year) values (748, 'Passat', 'Khaki', 2003);
insert into cars (id, model, color, release_year) values (749, 'LaCrosse', 'Aquamarine', 2008);
insert into cars (id, model, color, release_year) values (750, 'Yukon XL 2500', 'Khaki', 2004);
insert into cars (id, model, color, release_year) values (751, 'Liberty', 'Green', 2010);
insert into cars (id, model, color, release_year) values (752, 'Sonoma', 'Khaki', 1996);
insert into cars (id, model, color, release_year) values (753, 'Truck', 'Purple', 1996);
insert into cars (id, model, color, release_year) values (754, 'MR2', 'Indigo', 1987);
insert into cars (id, model, color, release_year) values (755, 'MR2', 'Red', 2003);
insert into cars (id, model, color, release_year) values (756, 'Colt Vista', 'Blue', 1993);
insert into cars (id, model, color, release_year) values (757, 'SC', 'Violet', 2008);
insert into cars (id, model, color, release_year) values (758, 'Excel', 'Fuscia', 1988);
insert into cars (id, model, color, release_year) values (759, 'Taurus', 'Mauv', 2008);
insert into cars (id, model, color, release_year) values (760, 'H1', 'Mauv', 1998);
insert into cars (id, model, color, release_year) values (761, 'Bonneville', 'Teal', 2002);
insert into cars (id, model, color, release_year) values (762, 'Blazer', 'Aquamarine', 1995);
insert into cars (id, model, color, release_year) values (763, 'Range Rover Sport', 'Mauv', 2009);
insert into cars (id, model, color, release_year) values (764, 'SL-Class', 'Orange', 2005);
insert into cars (id, model, color, release_year) values (765, 'MR2', 'Crimson', 2001);
insert into cars (id, model, color, release_year) values (766, 'TL', 'Puce', 2006);
insert into cars (id, model, color, release_year) values (767, 'Ion', 'Blue', 2007);
insert into cars (id, model, color, release_year) values (768, 'Sportage', 'Purple', 2008);
insert into cars (id, model, color, release_year) values (769, 'V8 Vantage', 'Blue', 2006);
insert into cars (id, model, color, release_year) values (770, '7 Series', 'Orange', 1997);
insert into cars (id, model, color, release_year) values (771, '4Runner', 'Yellow', 1992);
insert into cars (id, model, color, release_year) values (772, 'Grand Caravan', 'Aquamarine', 2002);
insert into cars (id, model, color, release_year) values (773, 'Golf', 'Blue', 2010);
insert into cars (id, model, color, release_year) values (774, 'Mazda6 5-Door', 'Fuscia', 2006);
insert into cars (id, model, color, release_year) values (775, 'Montana', 'Violet', 2000);
insert into cars (id, model, color, release_year) values (776, '7 Series', 'Purple', 2012);
insert into cars (id, model, color, release_year) values (777, 'LeSabre', 'Blue', 2002);
insert into cars (id, model, color, release_year) values (778, 'Capri', 'Mauv', 1991);
insert into cars (id, model, color, release_year) values (779, 'Esprit', 'Crimson', 1996);
insert into cars (id, model, color, release_year) values (780, 'STS', 'Indigo', 2007);
insert into cars (id, model, color, release_year) values (781, 'Vitara', 'Fuscia', 1999);
insert into cars (id, model, color, release_year) values (782, 'Roadster', 'Aquamarine', 2010);
insert into cars (id, model, color, release_year) values (783, 'Century', 'Crimson', 2002);
insert into cars (id, model, color, release_year) values (784, 'Gemini', 'Purple', 1988);
insert into cars (id, model, color, release_year) values (785, 'B-Series', 'Indigo', 1992);
insert into cars (id, model, color, release_year) values (786, 'VS Commodore', 'Red', 1995);
insert into cars (id, model, color, release_year) values (787, 'Pajero', 'Turquoise', 2002);
insert into cars (id, model, color, release_year) values (788, 'Avalanche 2500', 'Blue', 2002);
insert into cars (id, model, color, release_year) values (789, 'A3', 'Goldenrod', 2011);
insert into cars (id, model, color, release_year) values (790, 'CL', 'Pink', 2001);
insert into cars (id, model, color, release_year) values (791, 'RX-7', 'Orange', 1984);
insert into cars (id, model, color, release_year) values (792, '3 Series', 'Crimson', 1999);
insert into cars (id, model, color, release_year) values (793, 'Leone', 'Yellow', 1985);
insert into cars (id, model, color, release_year) values (794, 'xD', 'Goldenrod', 2008);
insert into cars (id, model, color, release_year) values (795, 'Range Rover', 'Maroon', 2004);
insert into cars (id, model, color, release_year) values (796, 'B-Series', 'Red', 1995);
insert into cars (id, model, color, release_year) values (797, 'Daewoo Lacetti', 'Violet', 2004);
insert into cars (id, model, color, release_year) values (798, 'Altima', 'Aquamarine', 2007);
insert into cars (id, model, color, release_year) values (799, 'Corvette', 'Pink', 1970);
insert into cars (id, model, color, release_year) values (800, 'Escalade EXT', 'Turquoise', 2008);
insert into cars (id, model, color, release_year) values (801, 'F250', 'Red', 1999);
insert into cars (id, model, color, release_year) values (802, 'Tahoe', 'Puce', 1997);
insert into cars (id, model, color, release_year) values (803, 'Torrent', 'Purple', 2006);
insert into cars (id, model, color, release_year) values (804, 'Sonata', 'Indigo', 2007);
insert into cars (id, model, color, release_year) values (805, 'Rally Wagon 1500', 'Red', 1993);
insert into cars (id, model, color, release_year) values (806, 'rio', 'Fuscia', 2001);
insert into cars (id, model, color, release_year) values (807, 'Sierra 2500', 'Blue', 2005);
insert into cars (id, model, color, release_year) values (808, 'EXP', 'Teal', 1987);
insert into cars (id, model, color, release_year) values (809, 'F-Series', 'Orange', 2009);
insert into cars (id, model, color, release_year) values (810, 'Brat', 'Puce', 1986);
insert into cars (id, model, color, release_year) values (811, 'GX', 'Violet', 2004);
insert into cars (id, model, color, release_year) values (812, 'Milan', 'Violet', 2007);
insert into cars (id, model, color, release_year) values (813, 'Patriot', 'Orange', 2007);
insert into cars (id, model, color, release_year) values (814, 'Dakota', 'Khaki', 2004);
insert into cars (id, model, color, release_year) values (815, 'LeMans', 'Orange', 1989);
insert into cars (id, model, color, release_year) values (816, 'GTO', 'Mauv', 1994);
insert into cars (id, model, color, release_year) values (817, 'Boxster', 'Orange', 1999);
insert into cars (id, model, color, release_year) values (818, 'R8', 'Mauv', 2010);
insert into cars (id, model, color, release_year) values (819, 'S4', 'Puce', 2013);
insert into cars (id, model, color, release_year) values (820, 'RX Hybrid', 'Yellow', 2008);
insert into cars (id, model, color, release_year) values (821, 'Aurora', 'Crimson', 1995);
insert into cars (id, model, color, release_year) values (822, 'F-Series', 'Green', 2008);
insert into cars (id, model, color, release_year) values (823, 'Miata MX-5', 'Yellow', 2006);
insert into cars (id, model, color, release_year) values (824, 'Sportage', 'Goldenrod', 1998);
insert into cars (id, model, color, release_year) values (825, 'Uplander', 'Purple', 2006);
insert into cars (id, model, color, release_year) values (826, 'Skyhawk', 'Maroon', 1984);
insert into cars (id, model, color, release_year) values (827, 'Ranger', 'Puce', 1992);
insert into cars (id, model, color, release_year) values (828, 'F250', 'Violet', 2007);
insert into cars (id, model, color, release_year) values (829, 'Skylark', 'Violet', 1997);
insert into cars (id, model, color, release_year) values (830, 'Lumina', 'Red', 1993);
insert into cars (id, model, color, release_year) values (831, 'Tiguan', 'Teal', 2009);
insert into cars (id, model, color, release_year) values (832, 'Yaris', 'Indigo', 2011);
insert into cars (id, model, color, release_year) values (833, 'Town & Country', 'Crimson', 1997);
insert into cars (id, model, color, release_year) values (834, 'Lancer', 'Indigo', 2004);
insert into cars (id, model, color, release_year) values (835, 'Aveo', 'Red', 2007);
insert into cars (id, model, color, release_year) values (836, 'Firebird', 'Indigo', 1995);
insert into cars (id, model, color, release_year) values (837, 'Avenger', 'Red', 2009);
insert into cars (id, model, color, release_year) values (838, 'Sorento', 'Goldenrod', 2007);
insert into cars (id, model, color, release_year) values (839, 'F250', 'Red', 1999);
insert into cars (id, model, color, release_year) values (840, 'G-Series 2500', 'Yellow', 1997);
insert into cars (id, model, color, release_year) values (841, 'Avalon', 'Teal', 2007);
insert into cars (id, model, color, release_year) values (842, 'MR2', 'Orange', 2002);
insert into cars (id, model, color, release_year) values (843, 'Skyhawk', 'Maroon', 1988);
insert into cars (id, model, color, release_year) values (844, 'xA', 'Goldenrod', 2006);
insert into cars (id, model, color, release_year) values (845, '100', 'Mauv', 1993);
insert into cars (id, model, color, release_year) values (846, '8 Series', 'Teal', 1997);
insert into cars (id, model, color, release_year) values (847, 'S10 Blazer', 'Orange', 1992);
insert into cars (id, model, color, release_year) values (848, 'Bonneville', 'Indigo', 1986);
insert into cars (id, model, color, release_year) values (849, 'C-Class', 'Green', 2012);
insert into cars (id, model, color, release_year) values (850, 'del Sol', 'Maroon', 1993);
insert into cars (id, model, color, release_year) values (851, 'GLK-Class', 'Maroon', 2012);
insert into cars (id, model, color, release_year) values (852, 'SLK-Class', 'Violet', 2003);
insert into cars (id, model, color, release_year) values (853, 'MPV', 'Violet', 2005);
insert into cars (id, model, color, release_year) values (854, 'Prius Plug-in', 'Indigo', 2012);
insert into cars (id, model, color, release_year) values (855, 'LS', 'Green', 2004);
insert into cars (id, model, color, release_year) values (856, 'Santa Fe', 'Aquamarine', 2008);
insert into cars (id, model, color, release_year) values (857, 'Celica', 'Maroon', 1994);
insert into cars (id, model, color, release_year) values (858, 'E-Class', 'Teal', 1993);
insert into cars (id, model, color, release_year) values (859, 'Mustang', 'Purple', 2003);
insert into cars (id, model, color, release_year) values (860, 'Sprinter', 'Green', 2010);
insert into cars (id, model, color, release_year) values (861, 'Sonoma', 'Puce', 1994);
insert into cars (id, model, color, release_year) values (862, 'Cougar', 'Green', 1990);
insert into cars (id, model, color, release_year) values (863, 'Coupe', 'Purple', 2005);
insert into cars (id, model, color, release_year) values (864, 'LS', 'Teal', 1990);
insert into cars (id, model, color, release_year) values (865, 'LeSabre', 'Purple', 1998);
insert into cars (id, model, color, release_year) values (866, 'Expedition EL', 'Goldenrod', 2011);
insert into cars (id, model, color, release_year) values (867, 'Esteem', 'Mauv', 1998);
insert into cars (id, model, color, release_year) values (868, 'Reatta', 'Teal', 1989);
insert into cars (id, model, color, release_year) values (869, 'Impala', 'Fuscia', 2001);
insert into cars (id, model, color, release_year) values (870, '2500 Club Coupe', 'Purple', 1997);
insert into cars (id, model, color, release_year) values (871, 'Mustang', 'Aquamarine', 1990);
insert into cars (id, model, color, release_year) values (872, 'Cougar', 'Puce', 1995);
insert into cars (id, model, color, release_year) values (873, 'Range Rover', 'Purple', 1990);
insert into cars (id, model, color, release_year) values (874, 'Pajero', 'Orange', 1992);
insert into cars (id, model, color, release_year) values (875, 'A6', 'Violet', 2010);
insert into cars (id, model, color, release_year) values (876, 'Passat', 'Indigo', 1996);
insert into cars (id, model, color, release_year) values (877, 'Expedition', 'Green', 2007);
insert into cars (id, model, color, release_year) values (878, 'Corolla', 'Violet', 1997);
insert into cars (id, model, color, release_year) values (879, 'Altima', 'Maroon', 2009);
insert into cars (id, model, color, release_year) values (880, 'Yukon XL 1500', 'Pink', 2011);
insert into cars (id, model, color, release_year) values (881, 'Range Rover Classic', 'Teal', 1993);
insert into cars (id, model, color, release_year) values (882, 'Esprit', 'Purple', 1997);
insert into cars (id, model, color, release_year) values (883, '745', 'Khaki', 2003);
insert into cars (id, model, color, release_year) values (884, 'GTO', 'Turquoise', 1990);
insert into cars (id, model, color, release_year) values (885, 'RX', 'Teal', 2013);
insert into cars (id, model, color, release_year) values (886, 'E-Series', 'Yellow', 1989);
insert into cars (id, model, color, release_year) values (887, 'Grand Caravan', 'Teal', 1996);
insert into cars (id, model, color, release_year) values (888, 'S60', 'Crimson', 2008);
insert into cars (id, model, color, release_year) values (889, 'Wrangler', 'Violet', 2002);
insert into cars (id, model, color, release_year) values (890, 'V70', 'Goldenrod', 2002);
insert into cars (id, model, color, release_year) values (891, 'Bronco II', 'Mauv', 1984);
insert into cars (id, model, color, release_year) values (892, '3 Series', 'Aquamarine', 2009);
insert into cars (id, model, color, release_year) values (893, 'Q', 'Violet', 2005);
insert into cars (id, model, color, release_year) values (894, 'Torrent', 'Purple', 2009);
insert into cars (id, model, color, release_year) values (895, 'S2000', 'Blue', 2002);
insert into cars (id, model, color, release_year) values (896, '929', 'Puce', 1992);
insert into cars (id, model, color, release_year) values (897, 'riolet', 'Mauv', 1992);
insert into cars (id, model, color, release_year) values (898, 'Sidekick', 'Red', 1996);
insert into cars (id, model, color, release_year) values (899, 'Aerostar', 'Turquoise', 1994);
insert into cars (id, model, color, release_year) values (900, 'Town & Country', 'Yellow', 2006);
insert into cars (id, model, color, release_year) values (901, 'Gemini', 'Goldenrod', 1986);
insert into cars (id, model, color, release_year) values (902, 'Cougar', 'Red', 1985);
insert into cars (id, model, color, release_year) values (903, 'Town & Country', 'Orange', 1993);
insert into cars (id, model, color, release_year) values (904, 'Highlander', 'Crimson', 2002);
insert into cars (id, model, color, release_year) values (905, 'Riviera', 'Indigo', 1979);
insert into cars (id, model, color, release_year) values (906, 'Thunderbird', 'Purple', 1977);
insert into cars (id, model, color, release_year) values (907, 'Windstar', 'Aquamarine', 1996);
insert into cars (id, model, color, release_year) values (908, 'GS', 'Khaki', 2007);
insert into cars (id, model, color, release_year) values (909, 'Century', 'Blue', 2002);
insert into cars (id, model, color, release_year) values (910, 'Mystique', 'Goldenrod', 1997);
insert into cars (id, model, color, release_year) values (911, '911', 'Khaki', 1998);
insert into cars (id, model, color, release_year) values (912, 'Pathfinder', 'Pink', 2006);
insert into cars (id, model, color, release_year) values (913, '911', 'Maroon', 2007);
insert into cars (id, model, color, release_year) values (914, 'Avenger', 'Pink', 2000);
insert into cars (id, model, color, release_year) values (915, 'Tacoma Xtra', 'Purple', 1998);
insert into cars (id, model, color, release_year) values (916, 'Altima', 'Red', 2002);
insert into cars (id, model, color, release_year) values (917, 'Intrepid', 'Aquamarine', 1996);
insert into cars (id, model, color, release_year) values (918, 'Corvette', 'Pink', 1993);
insert into cars (id, model, color, release_year) values (919, 'i-MiEV', 'Violet', 2012);
insert into cars (id, model, color, release_year) values (920, 'Bonneville', 'Teal', 2001);
insert into cars (id, model, color, release_year) values (921, 'Murano', 'Puce', 2003);
insert into cars (id, model, color, release_year) values (922, 'Elan', 'Maroon', 1992);
insert into cars (id, model, color, release_year) values (923, 'Aero 8', 'Aquamarine', 2007);
insert into cars (id, model, color, release_year) values (924, 'LS', 'Aquamarine', 1990);
insert into cars (id, model, color, release_year) values (925, 'Matrix', 'Orange', 2008);
insert into cars (id, model, color, release_year) values (926, 'Cayenne', 'Fuscia', 2011);
insert into cars (id, model, color, release_year) values (927, 'NSX', 'Orange', 1994);
insert into cars (id, model, color, release_year) values (928, 'Grand Prix', 'Maroon', 1963);
insert into cars (id, model, color, release_year) values (929, 'Altima', 'Teal', 2010);
insert into cars (id, model, color, release_year) values (930, 'Stanza', 'Maroon', 1992);
insert into cars (id, model, color, release_year) values (931, 'Civic', 'Goldenrod', 1989);
insert into cars (id, model, color, release_year) values (932, 'Suburban 2500', 'Teal', 1995);
insert into cars (id, model, color, release_year) values (933, '4Runner', 'Crimson', 2006);
insert into cars (id, model, color, release_year) values (934, 'G', 'Fuscia', 2010);
insert into cars (id, model, color, release_year) values (935, 'Grand Prix', 'Green', 1970);
insert into cars (id, model, color, release_year) values (936, 'Celica', 'Puce', 1994);
insert into cars (id, model, color, release_year) values (937, 'Mini Cooper S', 'Mauv', 1963);
insert into cars (id, model, color, release_year) values (938, 'Skyhawk', 'Orange', 1986);
insert into cars (id, model, color, release_year) values (939, 'Sportage', 'Mauv', 2007);
insert into cars (id, model, color, release_year) values (940, 'MKX', 'Indigo', 2012);
insert into cars (id, model, color, release_year) values (941, 'Veracruz', 'Red', 2008);
insert into cars (id, model, color, release_year) values (942, '9-3', 'Fuscia', 2011);
insert into cars (id, model, color, release_year) values (943, 'Lumina', 'Orange', 1998);
insert into cars (id, model, color, release_year) values (944, 'Elantra', 'Green', 2005);
insert into cars (id, model, color, release_year) values (945, 'Cougar', 'Mauv', 1997);
insert into cars (id, model, color, release_year) values (946, 'CR-V', 'Indigo', 2012);
insert into cars (id, model, color, release_year) values (947, 'MX-5', 'Blue', 2005);
insert into cars (id, model, color, release_year) values (948, 'S40', 'Orange', 2001);
insert into cars (id, model, color, release_year) values (949, 'Econoline E250', 'Khaki', 1997);
insert into cars (id, model, color, release_year) values (950, 'L300', 'Aquamarine', 1990);
insert into cars (id, model, color, release_year) values (951, 'V90', 'Pink', 1998);
insert into cars (id, model, color, release_year) values (952, 'Mirage', 'Red', 1995);
insert into cars (id, model, color, release_year) values (953, 'Forester', 'Crimson', 2002);
insert into cars (id, model, color, release_year) values (954, 'Range Rover', 'Puce', 2008);
insert into cars (id, model, color, release_year) values (955, 'Viper', 'Green', 1999);
insert into cars (id, model, color, release_year) values (956, 'Seville', 'Aquamarine', 1994);
insert into cars (id, model, color, release_year) values (957, 'ZDX', 'Puce', 2012);
insert into cars (id, model, color, release_year) values (958, '1500', 'Maroon', 1994);
insert into cars (id, model, color, release_year) values (959, 'Tucson', 'Green', 2007);
insert into cars (id, model, color, release_year) values (960, 'SSR', 'Crimson', 2003);
insert into cars (id, model, color, release_year) values (961, 'Continental Flying Spur', 'Puce', 2009);
insert into cars (id, model, color, release_year) values (962, 'Tacoma', 'Maroon', 1998);
insert into cars (id, model, color, release_year) values (963, 'Outback', 'Goldenrod', 2004);
insert into cars (id, model, color, release_year) values (964, 'Mustang', 'Red', 1986);
insert into cars (id, model, color, release_year) values (965, 'Gallardo', 'Crimson', 2007);
insert into cars (id, model, color, release_year) values (966, 'Thunderbird', 'Turquoise', 1980);
insert into cars (id, model, color, release_year) values (967, 'C70', 'Crimson', 2007);
insert into cars (id, model, color, release_year) values (968, 'G', 'Pink', 2000);
insert into cars (id, model, color, release_year) values (969, 'Envoy', 'Khaki', 2004);
insert into cars (id, model, color, release_year) values (970, 'Swift', 'Orange', 1988);
insert into cars (id, model, color, release_year) values (971, 'STS-V', 'Blue', 2008);
insert into cars (id, model, color, release_year) values (972, 'Durango', 'Goldenrod', 1998);
insert into cars (id, model, color, release_year) values (973, 'Starion', 'Crimson', 1985);
insert into cars (id, model, color, release_year) values (974, 'Mirage', 'Purple', 1984);
insert into cars (id, model, color, release_year) values (975, 'Avenger', 'Blue', 1995);
insert into cars (id, model, color, release_year) values (976, 'XK Series', 'Green', 2001);
insert into cars (id, model, color, release_year) values (977, 'Tercel', 'Puce', 1997);
insert into cars (id, model, color, release_year) values (978, 'Bonneville', 'Puce', 2003);
insert into cars (id, model, color, release_year) values (979, 'Mark LT', 'Indigo', 2008);
insert into cars (id, model, color, release_year) values (980, 'Aspire', 'Blue', 1997);
insert into cars (id, model, color, release_year) values (981, 'V8', 'Fuscia', 1990);
insert into cars (id, model, color, release_year) values (982, 'LeSabre', 'Teal', 1992);
insert into cars (id, model, color, release_year) values (983, 'Grand Cherokee', 'Mauv', 2000);
insert into cars (id, model, color, release_year) values (984, 'Z4', 'Indigo', 2003);
insert into cars (id, model, color, release_year) values (985, 'Beretta', 'Orange', 1993);
insert into cars (id, model, color, release_year) values (986, 'ES', 'Red', 2004);
insert into cars (id, model, color, release_year) values (987, 'Rogue', 'Blue', 2011);
insert into cars (id, model, color, release_year) values (988, 'Wrangler', 'Crimson', 2001);
insert into cars (id, model, color, release_year) values (989, 'Aveo', 'Goldenrod', 2011);
insert into cars (id, model, color, release_year) values (990, 'Discovery Series II', 'Orange', 1999);
insert into cars (id, model, color, release_year) values (991, 'Yukon XL 1500', 'Pink', 2010);
insert into cars (id, model, color, release_year) values (992, 'RL', 'Goldenrod', 2000);
insert into cars (id, model, color, release_year) values (993, 'Accord', 'Red', 2004);
insert into cars (id, model, color, release_year) values (994, 'IPL G', 'Fuscia', 2012);
insert into cars (id, model, color, release_year) values (995, 'CLK-Class', 'Violet', 2009);
insert into cars (id, model, color, release_year) values (996, 'Monterey', 'Teal', 2005);
insert into cars (id, model, color, release_year) values (997, 'A8', 'Teal', 1998);
insert into cars (id, model, color, release_year) values (998, 'Cougar', 'Aquamarine', 1967);
insert into cars (id, model, color, release_year) values (999, '350Z Roadster', 'Blue', 2006);
insert into cars (id, model, color, release_year) values (1000, 'Camaro', 'Aquamarine', 1975);
